server:
  port: 8093
#  session: stateless

spring:
  application:
    name: service-security3
#  security:
#    basic:
#      enabled: true
#    user:
#      name: user2
#      password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:123456@peer1:8761/eureka/
