server:
  port: 8092

spring:
  application:
    name: service-security2
  #  security:
  #    basic:
  #      enabled: true
  #    user:
  #      name: user1
  #      password: 123456
#  security:
#    oauth2:
#      client:
#        accessTokenUri: http://localhost:8080/authserver/oauth/token
#        userAuthorizationUri: http://localhost:8080/authserver/oauth/authorize
#        clientId: first
#        clientSecret: passwordforauthserver
#      resource:
#        userInfoUri: http://localhost:8080/user

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:123456@peer1:8761/eureka/

  #  security:
  #    basic:
  #      enabled: true
  #    user:
  #      name: user1
  #      password: 123456