eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: TransactionManager
  datasource:
  url: jdbc:mysql://127.0.0.1:3306/tx-manager?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver

server:
  port: 7970


