server:
  port: 8080

spring:
  application:
    name: service-oauth2
  security:
    basic:
      enabled: true
    user:
      name: user
      password: 123456

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:123456@peer1:8761/eureka/
