server:
  port: 8766
spring:
  application:
    name: service-hello
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    minIdle: 1
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    test-on-return: false
    test-on-borrow: false
    test-while-idle: true
    validation-query: select 'x'
    min-evictable-idle-time-millis: 300000
    time-between-eviction-runs-millis: 60000
    max-active: 20
    max-wait: 60000
    initial-size: 1
  redis:
    host: localhost
    port: 6379
    password:
mybatis:
  type-aliases-package: com.yfny.servicecommon.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
service:
  tips-url: http://localhost:8762/

